### ISSUE TITLE
Unable to switch collection in config.js on rinkeby

### ISSUE THREAD

**Issue by Quantmatic** [rarepress/rarepress#6]
Attempting to switch collection contract in config.js on Rinkeby results in an error 
https://github.com/rarepress/rarepress/blob/4199e1fbbdf04114bc7886c532d88837b79158a5/config.js#L224

this is the contract address I'm trying to switch to:
https://rinkeby.etherscan.io/address/0x9aaf5dfce77ea90ed4c8ad8c3f31d79d26e79bdd

which is the contract address of the ERC-721 collection I created on Rinkeby

```
const { createAvatar } = require('@dicebear/avatars');
const style = require('@dicebear/open-peeps');
const Rarepress = require('rarepress');
(async () => {
  const rarepress = new Rarepress();
  await rarepress.init({ network: "rinkeby" })
  for(let i=0; i<5; i++) {
    let svg = createAvatar(style, { seed: i.toString() });
    let cid = await rarepress.fs.add(Buffer.from(svg))
    let token = await rarepress.token.create({
      metadata: {
        name: `${i}`,
        description: `${i}.svg`,
        image: `/ipfs/${cid}`
      }
    })
    console.log("signedToken", token)
    await rarepress.fs.push(cid)
    await rarepress.fs.push(token.uri)
    let sent = await rarepress.token.send(token)
    console.log(`[${i}] published: https://rarible.com/token/${sent.id}`)
  }
})();
```

node index.js result:

```
? Enter decryption password **************
0x0b8D384b63a5e2428F649a43fE8B93627BE45cC4
create symlink fs/ipfs/bafkreicwapx3ttfyxv7nhsm55sry2ep66zb36wtwn7l7orcra7c6menmv4
create symlink fs/ipfs/bafkreih27ql5b2whd64mofk7kpdzi2z3bknyrgj5ho6e3ig24tgjfprw2q
signedToken {
  '@type': 'ERC721',
  tokenId: '5224955300835260294427255567953130853624358350524799379889027447527923782035',
  uri: '/ipfs/bafkreih27ql5b2whd64mofk7kpdzi2z3bknyrgj5ho6e3ig24tgjfprw2q',
  tokenURI: '/ipfs/bafkreih27ql5b2whd64mofk7kpdzi2z3bknyrgj5ho6e3ig24tgjfprw2q',
  contract: '0x80a527978a99fb6eaa93c34559e2e19749bc0b0b',
  creators: [
    {
      account: '0x0b8d384b63a5e2428f649a43fe8b93627be45cc4',
      value: 10000
    }
  ],
  royalties: [],
  signatures: [
    '0xc19a6a419b42e48ff62ed7132910905646ccc607c663567936fcdf5457c0cb81076a52563cc53fbcfbfb1991bd1281ca83077674eeb8cc3cd8b1f5a82bbc94091c'
  ],
  metadata: {
    name: '0',
    description: '0.svg',
    image: '/ipfs/bafkreicwapx3ttfyxv7nhsm55sry2ep66zb36wtwn7l7orcra7c6menmv4'
  }
}
Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/QmQKTR2qLMz226QBrL4NEFmRcym9JJKKywtD6bRrAYawrj
Swarm listening on /ip4/192.168.3.45/tcp/4002/p2p/QmQKTR2qLMz226QBrL4NEFmRcym9JJKKywtD6bRrAYawrj
Swarm listening on /ip4/10.0.0.34/tcp/4002/p2p/QmQKTR2qLMz226QBrL4NEFmRcym9JJKKywtD6bRrAYawrj
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/QmQKTR2qLMz226QBrL4NEFmRcym9JJKKywtD6bRrAYawrj
adding to ipfs...
success
adding to ipfs...
success
(node:13911) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (/Users/alphaseeker/Documents/NFT/generative-nft/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/alphaseeker/Documents/NFT/generative-nft/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/alphaseeker/Documents/NFT/generative-nft/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13911) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:13911) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^CIPFS Stoppped
```

**Comment by Quantmatic** [comment]
<img width="698" alt="Screenshot 2021-12-07 at 17 22 41" src="https://user-images.githubusercontent.com/27093143/145076618-450329b4-a313-4410-9940-6d6c9c5bccb4.png">
