### ISSUE TITLE
After many success Uploads i get throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by kingchenc** [rarepress/rarepress#8]
How can we fixx this error/crash after few success uploads?

i added a try and catch in the for loop in the rarepress-starter but cant handle this

```
create symlink fs/ipfs/bafybeid5no2e5usypdlrj5cwe3ryeb4tioymil2h47qdtx66lgk2gqf3r4
create symlink fs/ipfs/bafkreiawckto3gn2ewzgptgb7sofkkqyzikxzwca2tjynsjwjhqd3jlugi
adding to ipfs...
timeout. not yet replicated: bafybeid5no2e5usypdlrj5cwe3ryeb4tioymil2h47qdtx66lgk2gqf3r4
retrying...
timeout. not yet replicated: bafybeid5no2e5usypdlrj5cwe3ryeb4tioymil2h47qdtx66lgk2gqf3r4
retrying...
timeout. not yet replicated: bafybeid5no2e5usypdlrj5cwe3ryeb4tioymil2h47qdtx66lgk2gqf3r4
retrying...
timeout. not yet replicated: bafybeid5no2e5usypdlrj5cwe3ryeb4tioymil2h47qdtx66lgk2gqf3r4
retrying...
node:events:368
      throw er; // Unhandled 'error' event
      ^

TypeError: cb is not a function
    at C:\Users\xxx\node_modules\@motrix\nat-api\index.js:336:7
    at C:\Users\xxx\node_modules\@motrix\nat-api\lib\upnp\device.js:61:11
    at Parser.<anonymous> (C:\xxx\node_modules\xml2js\lib\parser.js:304:18)
    at Parser.emit (node:events:390:28)
    at SAXParser.onclosetag (C:\xxx\node_modules\xml2js\lib\parser.js:262:26)
    at emit (C:\xxx\node_modules\sax\lib\sax.js:624:35)
    at emitNode (C:\xxx\node_modules\sax\lib\sax.js:629:5)
    at closeTag (C:\xxx\node_modules\sax\lib\sax.js:889:7)
    at SAXParser.write (C:\xxx\node_modules\sax\lib\sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (C:\xxx\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (C:\xxx\node_modules\xml2js\lib\parser.js:5:59)
    at Request._callback (C:\xxx\node_modules\@motrix\nat-api\lib\upnp\device.js:53:16)
    at Request.self.callback (C:\xxx\node_modules\request\request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (C:\xxx\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:390:28)
Emitted 'error' event on Parser instance at:
    at Parser.exports.Parser.Parser.parseString (C:\xxx\node_modules\xml2js\lib\parser.js:327:16)
    at Parser.parseString (C:\xxx\node_modules\xml2js\lib\parser.js:5:59)
    [... lines matching original stack trace ...]
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (C:\xxx\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by kingchenc** [comment]
Its not a fixx, but i just write a second script, if the error comes and the script crash, just restart it... ^^
hope anyone have a right fixx for this
